# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  # 应用的访问路径
  servlet:
      context-path: /
  tomcat:
    #tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值100
      min-spare: 100

# 日志配置
logging:
  level:
    org.parsley: warn


# Spring配置
spring:
  # 用druid数据源配置数据库内容
  profiles:
    active: druid
  # servlet配置
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小，请求大小
      max-request-size: 20MB
  # spring-mvc配置
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.parsley.domain
